"""initial migration

Revision ID: fb4ea98ef429
Revises: a5f85ac3d2a5
Create Date: 2021-02-23 17:43:03.818030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb4ea98ef429'
down_revision = 'a5f85ac3d2a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('random')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('random', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
